export const ProductsConstants = {
  SOLD_OUT: 'Agotado',
  NEW_ITEM: 'Nuevo',
  ALMOST_SOLD_OUT: 'Casi Agotado',
  ONLY_X_QUANTITY: (q: number) => `Solo quedan ${q} unidades.`,
  ALMOST_SOLD_OUT_QUANTITY: 5,
  ADD_CART: 'Agregar al pedido',
  VIEW_CART: 'Ver Pedido',
  ORDER_BY_WHATSAPP: 'Pedir por Whatsapp',
  UPDATE_ORDER_IN_CART: 'Ir a Actualizar Pedido',
  UPDATE_CART: 'Atualizar Pedido',
  CONFIRM_CART_ORDER: 'Confirmar Pedido',
  SEND_CART: 'Enviar Pedido',
  NEXT: 'Siguiente',
};
