export enum EndpointsAndEntityStateKeys {
  REGISTER = 'register',
  LOGIN = 'login',
  BY_COMPANY = 'by-company',
  BY_CATEGORY = 'by-category',
  PER_CATEGORY = 'per-category',
  BY_PHONE = 'by-phone',
  BY_CLIENT = 'by-client',
  PRODUCT_SAMPLES = 'product-samples',
  BY_ID = 'by-id',
  BY_SLUG = 'by-slug',
  INFINITE_SCROLL_DATA = 'infinityScrollData',
  PENDING = 'pending',
  BY_REF_ID = 'by-ref-id',
}
